### ISSUE TITLE
Extra symbol(iqlaab) on the ayah word in the json files

### ISSUE THREAD

**Issue by AxelReid** [Tarteel-io/quran-assets#25]
Assalamualekum! First of all thank u for the amazing work

I've been building a quran app and in order to display ayah words in exact line as in mushafs I'm using the page separated json files but I encountered in many words an extra 'mim' symbol(iqlaab) added at the end of a word, this is one example [https://github.com/TarteelAI/quran-assets/blob/main/pages/600.json#L68](https://github.com/TarteelAI/quran-assets/blob/main/pages/600.json#L68)
There're more in the Surah al-g'oshiyah
The same situations exists in the related QUL resources
Does it have it a purpose I didn't understand?

**Comment by mmmoussa** [comment]
Wa alaykum al salam, the purpose is to render the text in the same way it appears in the Uthmani mushaf, as demonstrated here:
![Simulator Screenshot - iPhone 12 Pro Max - 2024-10-26 at 02 32 46](https://github.com/user-attachments/assets/4b078a06-4f42-4bda-b568-19b00b08a29a)
